### ISSUE TITLE
Failed to cross compile to windows on bundled mode

### ISSUE THREAD

**Issue by xyzaurora** [Hugal31/yara-rust#116]
Hey, while cross compiling to windows while bundling yara-sys I get the following error

```
/x86_64-w64-mingw32/bin/ld: cannot find -lyara: No such file or directory
```

Yes, I've checked `ldconfig -p`
```
	libyara.so.10 (libc6,x86-64) => /usr/local/lib/libyara.so.10
	libyara.so (libc6,x86-64) => /usr/local/lib/libyara.so
```

**Comment by ikrivosheev** [comment]
@xyzaurora, hello! Can you show your `Cargo.toml` file?

**Comment by Hugal31** [comment]
Is `/usr/local/lib/libyara.so.10` cross-compiled for Windows? (Isn't it .dll on windows?)

**Comment by ikrivosheev** [comment]
> Is `/usr/local/lib/libyara.so.10` cross-compiled for Windows? (Isn't it .dll on windows?)

I had other thoughts. It's look like @xyzaurora tried to compile static library.

**Comment by xyzaurora** [comment]
Yeah, im using the `bundled-4_3_0` feature
```toml
yara = { version = "0.19.0", features = ["bundled-4_3_0"] }
```

**Comment by ikrivosheev** [comment]
@xyzaurora I agree with @Hugal31 . It's a strange name for a library on the Windows platform.

**Comment by xyzaurora** [comment]
It is indeed not cross-compiled for windows, I realized that just now.

Thanks for the help!
