### ISSUE TITLE
Release 0.20.0 is not tagged

### ISSUE THREAD

**Issue by vthib** [Hugal31/yara-rust#120]
The crate is published at release 0.20.0, but there is no CHANGELOD.md update or github release.
From looking at the sources at the release, it looks like it was for yara 4.3.1, so I guess the current HEAD of master is the right one? Could you push a tag for this version?

**Comment by vthib** [comment]
The version fields in the Cargo.toml files is also at 0.19.0, which causes issus when trying to use a fork of the repo with cargo patches

**Comment by Hugal31** [comment]
Sorry, forgot to push. All done!
