### ISSUE TITLE
no field `tail` on type `&YR_MATCHES`

### ISSUE THREAD

**Issue by jthinking** [Hugal31/yara-rust#23]
```
error[E0609]: no field `head` on type `&YR_MATCHES`
  --> /home/bochao/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/yara-sys-0.6.0/src/lib.rs:41:14
   |
41 |         self.head
   |              ^^^^ unknown field
   |
   = note: available fields are: `count`, `__bindgen_anon_1`, `__bindgen_anon_2`
```

**Comment by Hugal31** [comment]
Hello, thanks for submitting an issue. 

Which Yara version are you using?

**Comment by jthinking** [comment]
@Hugal31 thanks, i just solved this proplem by setting the environment variable YARA_INCLUDE_DIR to the directory containing the yara.h file. [15#issuecomment-802657077](https://github.com/Hugal31/yara-rust/issues/15#issuecomment-802657077)

**Comment by jthinking** [comment]
and i found that a `}` missing in the example code of the README.md

**Comment by Hugal31** [comment]
Thanks, I've fixed it.
I also added an error if you are trying to build with the (default) bindgen feature with an old version of Yara.
