### ISSUE TITLE
scanner::test::scanner_scan_proc fails randomly on Windows

### ISSUE THREAD

**Issue by Hugal31** [Hugal31/yara-rust#25]
This can be see in some [Travis jobs](https://travis-ci.org/github/Hugal31/yara-rust/jobs/768577253): sometimes, the test `scanner::test::scanner_scan_proc` fails on Windows.

**Comment by Hugal31** [comment]
@Orycterope, since you introduce those tests, do you have an idea?
Maybe the process exit too early? 
An other way to do it would be to make the process wait for a signal instead of sleeping / pinging for a few seconds.

**Comment by Orycterope** [comment]
I'm gonna look into it !
