### ISSUE TITLE
Add support for external variables

### ISSUE THREAD

**Issue by rhaist** [Hugal31/yara-rust#4]
Many of the current yara rule sets out there are using external variables like `filename`.
Using a rule set with this variables without initializing them at compile time will result in CompileError.

An example for a implementation can be found in the Go bindings by @hillu:
https://godoc.org/github.com/hillu/go-yara#Compiler.DefineVariable

**Comment by Hugal31** [comment]
Added in [0.3.1](
https://docs.rs/yara/0.3.1/yara/struct.Compiler.html?search=#method.define_variable) :)
