### ISSUE TITLE
Vendored build fails from crates.io

### ISSUE THREAD

**Issue by Guiguiprim** [Hugal31/yara-rust#48]
With the following in Cargo.toml:
`yara = { version = "0.10", default-features = false, features = ["vendored", "bundled-4_1_2"] } `

The build fails with:
```
error: failed to run custom build command for `yara-sys v0.10.0`
Caused by:
  process didn't exit successfully: `/home/me/project/target/debug/build/yara-sys-b728990ce16f2f1e/build-script-build` (exit status: 1)
  --- stderr
  error occurred: File exists (os error 17)
```

Looking at `/home/me/project/target/debug/build/yara-sys-b728990ce16f2f1e/out`, there is a broken link `/home/me/project/target/debug/build/yara-sys-b728990ce16f2f1e/out/yara` to not existing `/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/yara-sys-0.10.0/yara`

For what I could piece together:
- `$REPO/yara-sys/yara` is a git sub-module pointing to `yara` sources
- `yara-sys/build.rs` points to it in vendored mode
- When publishing to crates.io the sub-module is not integrated to the archive (see https://static.crates.io/crates/yara-sys/yara-sys-0.10.0.crate, it is a `.tar.gz`)

So I guess in vendored mode the sources should be download if needed (or they should be included in the crates.io archive)

**Comment by Hugal31** [comment]
It should work now on 0.11.1. Sorry for the wait!
