### ISSUE TITLE
Read rules from memory

### ISSUE THREAD

**Issue by rhaist** [Hugal31/yara-rust#5]
It would be great if (compiled) rules could be loaded from memory instead of loading them from a file on disk:

[1] https://yara.readthedocs.io/en/v3.4.0/capi.html#saving-and-retrieving-compiled-rules
[2] https://github.com/hillu/go-yara/blob/v1.1.0/rules_yara34.go#L95

**Comment by Hugal31** [comment]
Sure! It should not be hard to add a `YrReadStream` and a `YrWriteStream` traits, and implement them for `Read` and `Write`.

**Comment by Hugal31** [comment]
`Rules::load_from_stream` and `Rules::save_to_stream` are available in v0.4.1.
