### ISSUE TITLE
Explicitly set the openssl include directory

### ISSUE THREAD

**Issue by rmccrystal** [Hugal31/yara-rust#99]
I am trying to compile this crate on Windows with openssl using `YARA_CRYPTO_LIB=openssl` to fix the issue described by #89 and it complains that it cannot find an openssl header file. I fixed the issue on my end by adding a manual call to `cc::Build::include` inside build.rs to my openssl include directory, but it doesn't seem like there is any way to do this with environment variables
```rust
        let mut cc = cc::Build::new();
        cc.include(&basedir)
            .include(basedir.join("include"))
            .include(basedir.join("modules"))
            .include("C:\\Program Files\\OpenSSL-Win64\\include");
```

**Comment by rmccrystal** [comment]
#98 fixes this

**Comment by ikrivosheev** [comment]
@rmccrystal can we close the issue?
